apiVersion : apps/v1
kind: Deployment
metadata:
  name: webapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi 
    spec:
      containers:
        - name: webapi 
          image: <ACR>.azurecr.io/k8sflask
          ports:
          - containerPort: 80
      imagePullSecrets:
      - name: k8s-secret  
          
